server:
  port: 8084
spring:
  application:
    name: profile-service

  flyway:
    enable: false

  datasource:
    url: jdbc:postgresql://localhost:5432/superfuse_db
    username: postgres
    password: Abes@2027
    driver-class-name: org.postgresql.Driver
